version: 2.1
jobs:
    aku1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: lscpu
    aku2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: lscpu
    aku3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: lscpu
    aku4:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: lscpu
workflows:
    version: 2.1
    build:
        jobs:
            - aku1
            - aku2
            - aku3
            - aku4